A=rgb2gray(imread('image8.jpg'));
B=myGaussianNoise (0,0.01);
C=myGaussianNoise (0,0.03);
D=myGaussianNoise (0.2,0.01);
E=myGaussianNoise (0.2,0.03);
B1= myGaussianFilter(B);
C1= myGaussianFilter(C); 
D1= myGaussianFilter(D); 
E1= myGaussianFilter(E); 

subplot(5,3,1),imshow(A),title('The original image');
subplot(5,3,2),imhist(A);
subplot(5,3,4),imshow(B),title('mean value=0,variance=0.01');
subplot(5,3,5),imhist(B);
subplot(5,3,6),imshow(B1),title('Replica of the left polluted image');
subplot(5,3,7),imshow(C),title('mean value=0,variance=0.03');
subplot(5,3,8),imhist(C);
subplot(5,3,9),imshow(C1),title('Replica of the left polluted image');
subplot(5,3,10),imshow(D),title('mean value=0.2,variance=0.01');
subplot(5,3,11),imhist(D);
subplot(5,3,12),imshow(D1),title('Replica of the left polluted image');
subplot(5,3,13),imshow(E),title('mean value=0.2,variance=0.03');
subplot(5,3,14),imhist(E);
subplot(5,3,15),imshow(E1),title('Replica of the left polluted image');
